// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA8-x4gUW1wA3arG_YcCzCnmNXtQxdgesQ',
    appId: '1:128731269426:web:f4c960a4557130845baf2b',
    messagingSenderId: '128731269426',
    projectId: 'bytelogik-75aa3',
    authDomain: 'bytelogik-75aa3.firebaseapp.com',
    storageBucket: 'bytelogik-75aa3.firebasestorage.app',
    measurementId: 'G-8VKT72M830',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDsuWye9SKkh-tdkxWVDbrgiRe0H7mhFZ0',
    appId: '1:128731269426:android:d52264d659d98b045baf2b',
    messagingSenderId: '128731269426',
    projectId: 'bytelogik-75aa3',
    storageBucket: 'bytelogik-75aa3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCyQWPyJl47CN2jjdYMsN_IlyuxZe1LXDc',
    appId: '1:128731269426:ios:b395cc12e608500f5baf2b',
    messagingSenderId: '128731269426',
    projectId: 'bytelogik-75aa3',
    storageBucket: 'bytelogik-75aa3.firebasestorage.app',
    iosBundleId: 'com.example.bytelogikTask',
  );
}
